spring.application.name=01_CHEAM_NORAKPANHA_PVH_SPRING_HOMEWORK002
spring.datasource.url = jdbc:postgresql://localhost:5432/hw_db
spring.datasource.username = postgres
spring.datasource.password = 123
spring.datasource.driver-class-name = org.postgresql.Driver