spring.application.name=01_CHEAM_NORAKPANHA_PVH_SPRING_HOMEWORK002
server.port = 9090
spring.datasource.url = jdbc:postgresql://localhost:5432/batis_db
spring.datasource.username = postgres
spring.datasource.password = 123
spring.datasource.driver-class-name = org.postgresql.Driver